import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

import "./globals.css";
// css for header

import type { Metadata } from "next";
import type { FC } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

const RootLayout: FC<Props> = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <h1 className="m-10 content-center text-center text-4xl">
          <Link href="/">DineOnCampus</Link>
        </h1>

        {children}
      </body>
    </html>
  );
};

export default RootLayout;
